#ifndef DA7280_PATTERNS_H
#define DA7280_PATTERNS_H

/* This file is generated by gen_patterns.py; do not edit by hand. */

#include <stdint.h>
#include <stddef.h>

#define PATTERN_MAP_SIZE 47

// One step of a vibration pattern
typedef struct {
    uint16_t duration_ms;
    uint8_t  force_pct;
} PatternStep;

// Map entry tying mass to a pattern array
typedef struct {
    uint16_t          mass_g;
    const PatternStep *steps;
    size_t            count;
} PatternMapEntry;

// pattern_0, mass = 17 g
static const PatternStep pattern_0[] = {
    { 100, 50 },
    { 300, 10 },
};

// pattern_1, mass = 17 g
static const PatternStep pattern_1[] = {
    { 200, 50 },
    { 300, 0 },
    { 200, 70 },
};

// pattern_2, mass = 17 g
static const PatternStep pattern_2[] = {
    { 300, 30 },
    { 300, 10 },
    { 300, 70 },
    { 300, 70 },
    { 200, 50 },
};

// pattern_3, mass = 17 g
static const PatternStep pattern_3[] = {
    { 100, 60 },
    { 300, 30 },
    { 300, 30 },
    { 300, 70 },
};

// pattern_4, mass = 17 g
static const PatternStep pattern_4[] = {
    { 300, 40 },
    { 300, 0 },
    { 300, 70 },
    { 100, 30 },
};

// pattern_5, mass = 17 g
static const PatternStep pattern_5[] = {
    { 100, 0 },
    { 100, 60 },
    { 300, 40 },
    { 200, 60 },
    { 100, 70 },
};

// pattern_6, mass = 17 g
static const PatternStep pattern_6[] = {
    { 300, 0 },
    { 100, 0 },
    { 200, 10 },
    { 200, 60 },
};

// pattern_7, mass = 24 g
static const PatternStep pattern_7[] = {
    { 200, 50 },
    { 100, 50 },
    { 300, 10 },
    { 300, 70 },
};

// pattern_8, mass = 24 g
static const PatternStep pattern_8[] = {
    { 200, 70 },
    { 200, 10 },
    { 300, 70 },
    { 100, 10 },
};

// pattern_9, mass = 24 g
static const PatternStep pattern_9[] = {
    { 300, 40 },
    { 300, 10 },
    { 300, 70 },
    { 300, 10 },
    { 300, 50 },
};

// pattern_10, mass = 24 g
static const PatternStep pattern_10[] = {
    { 300, 50 },
    { 300, 20 },
    { 200, 70 },
};

// pattern_11, mass = 24 g
static const PatternStep pattern_11[] = {
    { 300, 60 },
    { 100, 40 },
};

// pattern_12, mass = 24 g
static const PatternStep pattern_12[] = {
    { 200, 60 },
    { 200, 70 },
    { 100, 70 },
};

// pattern_13, mass = 30 g
static const PatternStep pattern_13[] = {
    { 300, 70 },
    { 300, 10 },
    { 300, 60 },
    { 100, 70 },
    { 200, 70 },
};

// pattern_14, mass = 30 g
static const PatternStep pattern_14[] = {
    { 100, 50 },
    { 300, 70 },
    { 300, 50 },
    { 200, 30 },
};

// pattern_15, mass = 35 g
static const PatternStep pattern_15[] = {
    { 100, 50 },
    { 200, 10 },
    { 300, 30 },
    { 300, 40 },
};

// pattern_16, mass = 35 g
static const PatternStep pattern_16[] = {
    { 200, 20 },
    { 300, 0 },
    { 100, 60 },
    { 200, 70 },
    { 300, 70 },
};

// pattern_17, mass = 40 g
static const PatternStep pattern_17[] = {
    { 100, 30 },
    { 200, 20 },
    { 300, 10 },
    { 300, 20 },
    { 200, 70 },
};

// pattern_18, mass = 40 g
static const PatternStep pattern_18[] = {
    { 200, 30 },
    { 300, 60 },
    { 100, 50 },
    { 200, 70 },
    { 100, 60 },
};

// pattern_19, mass = 40 g
static const PatternStep pattern_19[] = {
    { 300, 0 },
    { 300, 10 },
    { 300, 70 },
    { 200, 0 },
    { 100, 30 },
};

// pattern_20, mass = 40 g
static const PatternStep pattern_20[] = {
    { 200, 0 },
    { 100, 70 },
    { 200, 60 },
    { 200, 60 },
};

// pattern_21, mass = 40 g
static const PatternStep pattern_21[] = {
    { 100, 60 },
    { 200, 60 },
    { 100, 10 },
    { 300, 70 },
    { 100, 60 },
};

// pattern_22, mass = 40 g
static const PatternStep pattern_22[] = {
    { 200, 20 },
    { 100, 70 },
    { 100, 30 },
    { 100, 70 },
    { 300, 10 },
};

// pattern_23, mass = 40 g
static const PatternStep pattern_23[] = {
    { 100, 70 },
    { 300, 70 },
    { 200, 30 },
    { 100, 30 },
    { 200, 50 },
};

// pattern_24, mass = 17 g
static const PatternStep pattern_24[] = {
    { 100, 60 },
    { 200, 70 },
    { 300, 50 },
    { 200, 40 },
    { 300, 60 },
};

// pattern_25, mass = 17 g
static const PatternStep pattern_25[] = {
    { 100, 50 },
    { 200, 40 },
    { 200, 60 },
    { 200, 30 },
    { 300, 60 },
};

// pattern_26, mass = 17 g
static const PatternStep pattern_26[] = {
    { 300, 70 },
    { 100, 70 },
    { 100, 50 },
};

// pattern_27, mass = 17 g
static const PatternStep pattern_27[] = {
    { 300, 70 },
    { 100, 40 },
    { 100, 70 },
};

// pattern_28, mass = 17 g
static const PatternStep pattern_28[] = {
    { 100, 20 },
    { 300, 40 },
    { 100, 40 },
    { 100, 10 },
    { 200, 20 },
};

// pattern_29, mass = 17 g
static const PatternStep pattern_29[] = {
    { 100, 30 },
    { 200, 10 },
    { 200, 70 },
    { 200, 70 },
    { 100, 20 },
};

// pattern_30, mass = 24 g
static const PatternStep pattern_30[] = {
    { 200, 70 },
    { 300, 40 },
    { 200, 60 },
    { 300, 10 },
    { 300, 70 },
};

// pattern_31, mass = 30 g
static const PatternStep pattern_31[] = {
    { 200, 20 },
    { 300, 10 },
    { 300, 70 },
    { 100, 70 },
};

// pattern_32, mass = 30 g
static const PatternStep pattern_32[] = {
    { 100, 0 },
    { 300, 70 },
    { 300, 70 },
    { 200, 40 },
    { 100, 0 },
};

// pattern_33, mass = 30 g
static const PatternStep pattern_33[] = {
    { 300, 70 },
    { 100, 70 },
    { 200, 70 },
    { 300, 60 },
    { 100, 20 },
};

// pattern_34, mass = 30 g
static const PatternStep pattern_34[] = {
    { 200, 70 },
    { 100, 70 },
    { 300, 10 },
    { 300, 10 },
    { 200, 50 },
};

// pattern_35, mass = 30 g
static const PatternStep pattern_35[] = {
    { 200, 10 },
    { 300, 20 },
};

// pattern_36, mass = 30 g
static const PatternStep pattern_36[] = {
    { 200, 40 },
    { 100, 50 },
    { 200, 20 },
    { 100, 30 },
    { 200, 70 },
};

// pattern_37, mass = 35 g
static const PatternStep pattern_37[] = {
    { 100, 40 },
    { 300, 70 },
    { 300, 50 },
    { 100, 50 },
    { 100, 60 },
};

// pattern_38, mass = 35 g
static const PatternStep pattern_38[] = {
    { 200, 0 },
    { 300, 10 },
    { 300, 40 },
    { 200, 60 },
    { 300, 70 },
};

// pattern_39, mass = 35 g
static const PatternStep pattern_39[] = {
    { 100, 30 },
    { 300, 60 },
    { 100, 30 },
    { 100, 60 },
    { 300, 60 },
};

// pattern_40, mass = 35 g
static const PatternStep pattern_40[] = {
    { 300, 30 },
    { 100, 40 },
    { 300, 40 },
    { 100, 20 },
    { 100, 50 },
};

// pattern_41, mass = 35 g
static const PatternStep pattern_41[] = {
    { 200, 70 },
    { 300, 70 },
    { 200, 50 },
    { 200, 40 },
    { 200, 70 },
};

// pattern_42, mass = 40 g
static const PatternStep pattern_42[] = {
    { 200, 20 },
    { 300, 50 },
    { 300, 70 },
    { 100, 50 },
    { 300, 70 },
};

// pattern_43, mass = 40 g
static const PatternStep pattern_43[] = {
    { 100, 40 },
    { 200, 30 },
    { 100, 40 },
    { 100, 40 },
    { 300, 20 },
};

// pattern_44, mass = 40 g
static const PatternStep pattern_44[] = {
    { 300, 70 },
    { 100, 70 },
    { 100, 40 },
    { 300, 60 },
};

// pattern_45, mass = 40 g
static const PatternStep pattern_45[] = {
    { 200, 0 },
    { 100, 20 },
    { 300, 60 },
    { 300, 70 },
    { 200, 50 },
};

// pattern_46, mass = 40 g
static const PatternStep pattern_46[] = {
    { 200, 0 },
    { 300, 30 },
    { 300, 40 },
    { 300, 70 },
    { 200, 50 },
};

const PatternMapEntry pattern_map[] = {
    { 17, pattern_0, 2 },
    { 17, pattern_1, 3 },
    { 17, pattern_2, 5 },
    { 17, pattern_3, 4 },
    { 17, pattern_4, 4 },
    { 17, pattern_5, 5 },
    { 17, pattern_6, 4 },
    { 24, pattern_7, 4 },
    { 24, pattern_8, 4 },
    { 24, pattern_9, 5 },
    { 24, pattern_10, 3 },
    { 24, pattern_11, 2 },
    { 24, pattern_12, 3 },
    { 30, pattern_13, 5 },
    { 30, pattern_14, 4 },
    { 35, pattern_15, 4 },
    { 35, pattern_16, 5 },
    { 40, pattern_17, 5 },
    { 40, pattern_18, 5 },
    { 40, pattern_19, 5 },
    { 40, pattern_20, 4 },
    { 40, pattern_21, 5 },
    { 40, pattern_22, 5 },
    { 40, pattern_23, 5 },
    { 17, pattern_24, 5 },
    { 17, pattern_25, 5 },
    { 17, pattern_26, 3 },
    { 17, pattern_27, 3 },
    { 17, pattern_28, 5 },
    { 17, pattern_29, 5 },
    { 24, pattern_30, 5 },
    { 30, pattern_31, 4 },
    { 30, pattern_32, 5 },
    { 30, pattern_33, 5 },
    { 30, pattern_34, 5 },
    { 30, pattern_35, 2 },
    { 30, pattern_36, 5 },
    { 35, pattern_37, 5 },
    { 35, pattern_38, 5 },
    { 35, pattern_39, 5 },
    { 35, pattern_40, 5 },
    { 35, pattern_41, 5 },
    { 40, pattern_42, 5 },
    { 40, pattern_43, 5 },
    { 40, pattern_44, 4 },
    { 40, pattern_45, 5 },
    { 40, pattern_46, 5 },
};

#endif // DA7280_PATTERNS_H
